language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install cython
  - pip install -r requirements.txt
script:
  - python setup.py install
  - nose2 -v gendis
  - python -m doctest -v gendis/genetic.py